### PR TITLE
added black code formatter and github action to run linting for PR and push #65

### PR DESCRIPTION
**Pull request by neelabalan**

### CODE REVIEW

**Comment by danionescu0** [comment]
It failed the lint on pull request

**Comment by neelabalan** [comment]
yeah I raised a PR with three commits only the last one has code formatted

**Comment by neelabalan** [comment]
the previous two commits failed the lint :)

**Comment by neelabalan** [comment]
the stresstest-locust directory doesn't seem to be formatted. I will why that happened and raise a PR for that

**Comment by danionescu0** [comment]
Hmm that is a diffrent directory ment to be run in the linux console not in the containers. Maybe we should exclude it for now

**Comment by neelabalan** [comment]
yeah I've already done that in black.yml to check only tests/ and python/ but don't know why it is taking locust for format. I think I am doing it wrong. I am looking at another option to exclude only locust with `black --check --exclude '/(stresstest-locusts)/' .` which works locally but not in github actions. I am working on this now.

**Pull request merged**
